- name: "Configuring yum for docker software"
  yum_repository:
        file: "docker_repo"
        baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable/"
        name: "docker"
        gpgcheck: no
        description: "docker repo"

- name: "Docker Installation"
  package:
        name: "docker-ce-18.09.1-3.el7.x86_64"
        state: present

- name: "Starting Docker service"
  service:
       name: "docker"
       state: started
       enabled: yes

