- name: "Install aptitude using apt"
  apt:
      name: "aptitude"
      state: latest
      update_cache: yes
      force_apt_get: yes


- name: "Install required system packages"
  apt:
      name: "{{ item }}"
      state: latest
      loop: "{{ required_apt_package}}"

- name: "Add Docker GPG apt Key"
  apt_key:
      url: "{{ apt_key }}"
      state: present

- name: "Add Docker Repository"
  apt_repository:
      repo: "{{ apt_repository_url }}"
      state: present

- name: "Install Docker-ce package"
  package:
      name: "{{ docker_package }}"
      state: "{{ docker_package_state }}"

- name: "Starting Docker Service"
  service:
       name: "docker"
       state: started
       enabled: yes
